#!/usr/bin/env zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified by
# $PROJECTS.  Typically I use it like:
#
#    c libr<tab>
#
# ...to quickly jump into librealsense, for example.
#
# I organised my projects folder into subdirectories (e.g. Personal, Uni etc)
# which are also completed automatically.

cd "$PROJECTS/$1" || exit
