#!/bin/sh
#
# Usage: find_in_topics <find-compatible arguments>
# Description: Find files in the topic dirs for the current OS which match 
# 	a given pattern. All args are passed to find builtin.
# Note: Used by the setup script and .zshrc
# 
# Author: Matthew Edwards

find_in_topics() {
  local exclude=("-not" "-path" "*/.git*")
  case "$(uname)" in
    Darwin)
      exclude+=("-not" "-path" "*/linux-only/*");;
    Linux)
      exclude+=("-not" "-path" "*/osx-only/*");;
  esac

  find -H "$DOTFILES" "${exclude[@]}" "$@"      
}
