#!/usr/bin/env zsh
# Usage: find_in_topics <find-compatible arguments>
# Find files in the topic dirs for the current OS which match
# a given pattern. All args are passed to find builtin.
# Note: Used by the setup script and .zshrc
#
# Author: Matthew Edwards

find_in_topics() {
  local -a exclude
  exclude=("-not" "-path" "*/.git*")
  exclude+=("-not" "-path" "*.noexec/*")
  case "$(uname)" in
    Darwin)
      exclude+=("-not" "-path" "*/linux-only/*");;
    Linux)
      exclude+=("-not" "-path" "*/osx-only/*");;
  esac

  local files
  files="$(find -H "$DOTFILES" "${exclude[@]}" "$@")"

  # Sort files so that *.1.zsh comes before *.2.zsh comes before everything else
  echo "$files" | rev | sort | rev
}
