#!/usr/bin/env bash
#
# Perform initial setup

cd "$(dirname "$0")"
export DOTFILES=$(pwd -P)

source $DOTFILES/functions/find_in_topics
source $DOTFILES/setup_common.sh

# Link dotfiles into home directory
install_dotfiles () {
  info "Installing dotfiles"

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find_in_topics -name "*.symlink"); do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

# Run all files named 'install.sh' in topic dirs.
run_installers() {
  info "Running installers..."

  for installer in $(find_in_topics -name install.sh); do
    sh -c "$installer"  || fail "$installer failed"
  done
}

# Install dotfiles and re-source bashrc before running installers, so HOMEBREW_CASK_OPTS is set
install_dotfiles
source ~/.bashrc
run_installers

echo ''
echo '  All installed!'
