#!/usr/bin/env bash
#
# Perform initial setup
# shellcheck disable=SC1090

set -e

cd "$(dirname "$0")"
DOTFILES=$(pwd -P)
export

source "$DOTFILES/functions/find_in_topics"
source "$DOTFILES/setup_common.sh"

# Link dotfiles into home directory
install_dotfiles () {
  info "Installing dotfiles"

  # shellcheck disable=SC2034
  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find_in_topics -name "*.symlink"); do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

# Run all files named 'install.sh' in topic dirs.
run_installers() {
  info "Running installers..."

  for installer in $(find_in_topics -name install.sh); do
    bash -c "$installer"  || fail "$installer failed"
  done
}

# Install dotfiles and re-source bashrc before running installers, so HOMEBREW_CASK_OPTS is set
install_dotfiles
source ~/.bashrc
run_installers

echo ''
info 'All installed!'
