#!/bin/sh
# Place an external screen above the laptop's Retina screen
#TODO: Generalize


case "$1" in
1080-above)
	xrandr --output eDP-1  --scale 1x1 --auto --pos 320x2160
	xrandr --output HDMI-1 --scale 2x2 --auto --fb 3840x3760 --pos 0x0
	;;
1200-above)
	xrandr --output eDP-1  --scale 1x1 --auto --pos 320x2400
	xrandr --output HDMI-3 --scale 2x2 --auto --fb 3840x4000 --pos 0x0
	;;
*)
	echo "Usage: $0 {1080-above|1200-above}"
	exit 1
esac
