alias db='docker build'
alias dr='docker run'
alias dri='docker run --rm --interactive --tty --init'
alias dris='dri --volume "$(pwd):/src" --workdir /src'
alias drx='dri --volume "/tmp/.X11-unix:/tmp/.X11-unix" --env DISPLAY=$DISPLAY'
