#!/usr/bin/env bash
#
# Run all any files named 'install/sh' in topic dirs.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
