name: Run tests
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        version: 3.7
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pexpect pytest
    - name: Run tests
      run: |
        pytest
